Libraries

In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB

Read data

In [33]:
train = pd.read_csv('train.csv')
test=pd.read_csv('Test.csv')

In [35]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8143 entries, 0 to 8142
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Temperature    8143 non-null   float64
 1   Humidity       8143 non-null   float64
 2   Light          8143 non-null   float64
 3   CO2            8143 non-null   float64
 4   HumidityRatio  8143 non-null   float64
 5   Occupancy      8143 non-null   int64  
dtypes: float64(5), int64(1)
memory usage: 381.8 KB


In [37]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2665 entries, 0 to 2664
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Temperature    2665 non-null   float64
 1   Humidity       2665 non-null   float64
 2   Light          2665 non-null   float64
 3   CO2            2665 non-null   float64
 4   HumidityRatio  2665 non-null   float64
 5   Occupancy      2665 non-null   int64  
dtypes: float64(5), int64(1)
memory usage: 125.1 KB


In [39]:
train

Temperature  Humidity  Light         CO2  HumidityRatio  Occupancy
0           23.18   27.2720  426.0  721.250000       0.004793          1
1           23.15   27.2675  429.5  714.000000       0.004783          1
2           23.15   27.2450  426.0  713.500000       0.004779          1
3           23.15   27.2000  426.0  708.250000       0.004772          1
4           23.10   27.2000  426.0  704.500000       0.004757          1
...           ...       ...    ...         ...            ...        ...
8138        21.05   36.0975  433.0  787.250000       0.005579          1
8139        21.05   35.9950  433.0  789.500000       0.005563          1
8140        21.10   36.0950  433.0  798.500000       0.005596          1
8141        21.10   36.2600  433.0  820.333333       0.005621          1
8142        21.10   36.2000  447.0  821.000000       0.005612          1

[8143 rows x 6 columns]

In [41]:
train.head()

Temperature  Humidity  Light     CO2  HumidityRatio  Occupancy
0        23.18   27.2720  426.0  721.25       0.004793          1
1        23.15   27.2675  429.5  714.00       0.004783          1
2        23.15   27.2450  426.0  713.50       0.004779          1
3        23.15   27.2000  426.0  708.25       0.004772          1
4        23.10   27.2000  426.0  704.50       0.004757          1

In [43]:
train.shape

(8143, 6)

In [45]:
test.shape

(2665, 6)

creating train and test for independent and dependent varaibles

In [49]:
x_t= train.drop('Occupancy',axis=1)
y_t=train['Occupancy']
x_test=test.drop('Occupancy',axis=1)
y_test=test['Occupancy']

feature scaling

In [59]:
from sklearn.preprocessing import StandardScaler
s=StandardScaler()
x_t=s.fit_transform(x_t)
x_test=s.fit_transform(x_test)

In [61]:
x_t

array([[2.51847007, 0.27852622, 1.57376283, 0.36494808, 1.09175673],
       [2.48896731, 0.27771261, 1.59173515, 0.34188106, 1.080555  ],
       [2.48896731, 0.27364453, 1.57376283, 0.34029023, 1.07588869],
       ...,
       [0.47294534, 1.87375407, 1.60970748, 0.61073113, 2.033527  ],
       [0.47294534, 1.90358662, 1.60970748, 0.68019732, 2.06381051],
       [0.47294534, 1.89273842, 1.68159679, 0.68231843, 2.05279885]])

In [63]:
x_test

array([[2.20476235, 0.37681367, 1.56686218, 0.10694007, 1.20754018],
       [2.22227495, 0.38420166, 1.53968001, 0.14521407, 1.22146087],
       [2.23395002, 0.35957501, 1.51676171, 0.17688126, 1.20916191],
       ...,
       [2.81770341, 0.14203962, 2.4934545 , 1.39390353, 1.33301316],
       [2.84364801, 0.14203962, 2.47746498, 1.38433502, 1.34579044],
       [2.89391566, 0.13451481, 2.41750431, 1.38775235, 1.36487283]])

Encoding categorical Values

In [68]:
from sklearn.preprocessing import LabelEncoder
l_y= LabelEncoder()
y_t=l_y.fit_transform(y_t)
y_test=l_y.fit_transform(y_test)

In [70]:
y_t

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

In [72]:
y_test

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

Naive Bayes Model Accuracy

In [76]:
NO=GaussianNB()
NO.fit(x_t,y_t)
print(NO.score(x_t,y_t))
print(NO.score(x_test,y_test))

0.9788775635515167
0.9039399624765478


Predicting values for test data

In [81]:
N_pred= NO.predict(x_test)

Confusion matrix for the model

In [84]:
n_r=confusion_matrix(y_test,N_pred)
print(n_r)

[[1682   11]
 [ 245  727]]
